### PR TITLE
added index.html file.

### PR DESCRIPTION
**Pull request by leightonrodney**
- Created index.html file
- Added h1 to that file

### CODE REVIEW

**Comment by vickydeso** [comment]
Looks good to me!

**Comment by leightonrodney** [comment]
> Looks good to me!

Thanks! Is there anything I need to change?

**Review by vickydeso — CHANGES_REQUESTED** [review]
You should add a paragraph

**Comment by leightonrodney** [comment]
> You should add a paragraph

I've added in the paragraph, can you re-review please?

**Review by vickydeso — APPROVED** [review]
Looks good to me!

**Pull request merged**
